name: localization_example
description: A new Routed application.
tags:
  - example
  - routed

version: 0.1.0
publish_to: "none"

funding:
  - https://www.buymeacoffee.com/kingwill101

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  args: ^2.5.0
  routed:
    path: ../../packages/routed

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
