name: kitchen_sink_example
publish_to: none
funding:
  - https://www.buymeacoffee.com/kingwill101

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

dependencies:
  routed:
  http: ^1.5.0
  uuid: ^4.5.1
  file: ^7.0.1
  collection:
dev_dependencies:
  routed_testing:
  server_testing:
tags:
  - example
  - routed

