name: inertia_dart
description: Dart implementation of Inertia.js protocol
version: 1.0.0
repository: https://github.com/kingwill101/routed_ecosystem/tree/master/packages/inertia
tags:
  - inertia
  - spa
  - server
  - http
  - react
  - vue
  - svelte

resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  http: ^1.6.0
  json_annotation: ^4.9.0
  meta: ^1.18.0
  server_testing: ^0.3.1
  test: any

dev_dependencies:
  build_runner: ^2.10.5
  coverage: ^1.15.0
  json_serializable: ^6.8.0
  lints: ^6.0.0
