name: routed_cli
description: Command-line tooling for the Routed framework with project scaffolding and management commands.
version: 0.2.1+1
repository: https://github.com/kingwill101/routed/tree/master/packages/routed_cli
tags:
  - cli
  - routed
  - scaffolding

funding:
  - https://www.buymeacoffee.com/kingwill101

resolution: workspace
environment:
  sdk: '>=3.9.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  args: ^2.7.0
  watcher: ^1.1.4
  stream_transform: ^2.1.1
  file: ^7.0.1
  yaml: ^3.1.2
  json2yaml: ^3.0.1
  routed: ^0.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  hotreloader: ^4.3.0
executables:
  routed: routed_cli
