name: routed_ecosystem
publish_to: none
workspace:
  - packages/routed
  - packages/routed_auth
  - packages/routed_hotwire
  - packages/inertia
  - packages/routed_inertia
  - packages/server_testing/server_testing
  - packages/server_testing/routed_testing
  - packages/server_testing/server_testing_shelf
  - packages/property_testing
  - examples/kitchen_sink
  - examples/config_demo
  - examples/openapi
  - examples/policy_demo/policy_demo
  - examples/demo_app
  - examples/contacts_app

funding:
  - https://www.buymeacoffee.com/kingwill101

environment:
  sdk: ">=3.9.0 <4.0.0"
dependencies:
  contextual: ^2.2.0
  liquify: ^1.4.2
  uuid: ^4.5.2

dev_dependencies:
  lints: ^6.0.0

tags:
  - workspace
