name: routed_ecosystem
publish_to: none
workspace:
  - packages/routed
  - packages/routed_cli
  - packages/routed_hotwire
  - packages/server_testing/server_testing
  - packages/server_testing/routed_testing
  - packages/server_testing/server_testing_shelf
  - packages/property_testing
  - examples/kitchen_sink
  - examples/config_demo
  - examples/openapi

funding:
  - https://www.buymeacoffee.com/kingwill101

environment:
  sdk: ">=3.9.0 <4.0.0"
dependencies:
  contextual: ^2.0.0
  liquify: ^1.3.1
  uuid: ^4.5.2
tags:
  - workspace

