name: routed_ecosystem
publish_to: none
workspace:
  - packages/routed
  - packages/routed_cli
  - packages/routed_hotwire
  - packages/class_view/simple_blog
  - packages/class_view/class_view
  - packages/class_view/routed_class_view
  - packages/class_view/shelf_class_view
  - packages/class_view/todo_test
  - packages/class_view/class_view_image_field
  - packages/server_testing/server_testing
  - packages/server_testing/routed_testing
  - packages/server_testing/server_testing_shelf
  - packages/property_testing
  - examples/kitchen_sink
  - examples/config_demo
  - packages/jaspr_routed/example
  - packages/jaspr_routed

funding:
  - https://www.buymeacoffee.com/kingwill101

environment:
  sdk: ">=3.9.0 <4.0.0"
dependencies:
  contextual: ^2.0.0
  liquify: ^1.3.1
  uuid: ^4.5.2
