name: server_testing
description: Reusable server testing library for Dart.
version: 0.2.0
repository: https://github.com/kingwill101/routed/tree/master/packages/server_testing/server_testing
tags:
  - server-testing
  - testing
  - server
  - testing-library

resolution: workspace
environment:
  sdk: '>=3.9.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  archive: ^4.0.7
  assertable_json: ^0.2.1
  build: ^4.0.2
  contextual: ^2.0.0
  crypto: ^3.0.6
  html: ^0.15.6
  http: ^1.5.0
  http_parser: ^4.1.2
  meta: ^1.17.0
  mockito: ^5.5.1
  path: ^1.9.1
  stack_trace: ^1.12.1
  #  routed: 0.0.1
  test: ^1.26.3
  webdriver: ^3.1.0
  yaml: ^3.1.3

dev_dependencies:
  build_config: ^1.2.0
  build_runner: ^2.10.1
  lints: ^6.0.0
  property_testing: ^0.2.0
  routed: ^0.2.0
  routed_testing: ^0.2.0
  very_good_analysis: ^10.0.0

executables:
  server_testing:
