name: server_testing
description: Reusable server testing library for Dart.
version: 0.3.1
repository: https://github.com/kingwill101/routed/tree/master/packages/server_testing
funding:
  - https://www.buymeacoffee.com/kingwill101

tags:
  - server-testing
  - testing
  - server
  - testing-library

resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  archive: ^4.0.7
  artisanal: ^0.1.1
  assertable_json: ^0.2.1
  build: ^4.0.3
  contextual: ^2.1.0
  crypto: ^3.0.7
  html: ^0.15.6
  http: ^1.6.0
  http_parser: ^4.1.2
  meta: ^1.17.0
  mockito: ^5.6.1
  path: ^1.9.1
  stack_trace: ^1.12.1
  #  routed: 0.0.1
  test: ^1.29.0
  webdriver: ^3.1.0
  yaml: ^3.1.3

dev_dependencies:
  build_config: ^1.2.0
  build_runner: ^2.10.4
  lints: ^6.0.0
  property_testing: ^0.3.1
  very_good_analysis: ^10.0.0

executables:
  server_testing:
