name: static_mounts
description: A new Routed application.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  args: ^2.5.0
  routed:
    path: ../../packages/routed

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3

