language = "C"
pragma_once = true
usize_is_size_t = true
no_includes = true
after_includes = """
typedef signed int int32_t;
typedef unsigned int uint32_t;
typedef unsigned short uint16_t;
typedef unsigned char uint8_t;
typedef unsigned long long uint64_t;
"""
