name: project_commands_demo
description: Example Routed project demonstrating custom CLI commands.
tags:
  - example
  - routed

publish_to: 'none'
version: 0.1.0

funding:
  - https://www.buymeacoffee.com/kingwill101

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  args: ^2.7.0
  routed:
    path: ../../packages/routed