name: routed_inertia
description: Inertia.js integration for the Routed framework
version: 1.0.0
repository: https://github.com/kingwill101/routed_ecosystem/tree/master/packages/routed_inertia
tags:
  - routed
  - inertia
  - server

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

dependencies:
  inertia_dart: ^0.1.0
  routed: ^0.3.2
  json_schema_builder: ^0.1.3
  meta: ^1.18.0

dev_dependencies:
  coverage: ^1.15.0
  test: ^1.29.0
  lints: ^6.0.0
  routed_testing: ^0.3.2
  server_testing: ^0.3.1
  file: ^7.0.1
