name: openapi_demo
description: A new Routed application.
version: 0.1.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  args: ^2.5.0
  artisanal: ^0.1.2
  routed: ^0.3.3

dev_dependencies:
  lints: ^6.0.0
  routed_testing: ^0.3.2
  server_testing: ^0.3.2
  test: ^1.26.3

