name: bench_routed
version: 0.1.0
description: Baseline routed server for benchmarks.
environment:
  sdk: ">=3.9.0 <4.0.0"
dependencies:
  routed:
    path: ../../../packages/routed
  sentry: ^9.10.0
