name: class_view
description: A class-based view system for Dart web frameworks
version: 0.1.0

# repository: https://github.com/my_org/my_repo
funding:
  - https://www.buymeacoffee.com/kingwill101

resolution: workspace
environment:
  sdk: ">=3.9.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  path: any
  acanthis: any
  timezone: any
  intl: any
  decimal: any
  meta: any
  liquify: ^1.3.0
  http_parser: ^4.1.2
dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  mockito: ^5.5.1
  build_runner: ^2.9.0
  server_testing:
  server_testing_shelf:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
