name: routed
description: A modular HTTP engine and routing framework for Dart with middleware, configuration, sessions, and observability built in.
version: 0.3.1
repository: https://github.com/kingwill101/routed/tree/master/packages/routed
tags:
  - routing
  - server
  - http

funding:
  - https://www.buymeacoffee.com/kingwill101

resolution: workspace


environment:
  sdk: ">=3.9.0 <4.0.0"

executables:
  routed: routed

# Add regular dependencies here.
dependencies:
  acanthis: ^1.5.1
  analyzer: ^10.0.1
  args: ^2.7.0
  build: ^4.0.4
  collection: ^1.19.1
  contextual: ^2.2.0
  dartastic_opentelemetry: ^0.9.3
  dartastic_opentelemetry_api: ^0.8.7
  decimal: ^3.2.4
  dotenv: ^4.2.0
  es_compression: ^2.0.15
  event_bus: ^2.0.1
  file: ^7.0.1
  file_cloud: ^0.1.0
  fuzzywuzzy: ^1.2.0
  glob: ^2.1.3
  http: ^1.6.0
  http2: ^2.3.1
  http_parser: ^4.1.2
  image: ^4.7.2
  intl: ^0.20.2
  jose: ^0.3.5
  json2yaml: ^3.0.1
  json_annotation: ^4.9.0
  json_schema_builder: ^0.1.3
  liquify: ^1.4.2
  meta: ^1.18.0
  mime: ^2.0.0
  mustache_template: ^2.0.3
  path: ^1.9.1
  pointycastle: ^4.0.0
  redis: ^4.0.0
  sentry: ^9.10.0
  shelf: ^1.4.2
  stack_trace: ^1.12.1
  storage_fs: ^0.1.0
  stream_transform: ^2.1.1
  timezone: ^0.11.0
  uuid: ^4.5.2
  watcher: ^1.2.1
  xml: ^6.6.1
  yaml: ^3.1.3
dev_dependencies:
  build_runner: ^2.10.5
  coverage: ^1.15.0
  lints: ^6.0.0
  property_testing: ^0.3.1
  routed_testing: ^0.3.1
  server_testing: ^0.3.1
  test: ^1.29.0
