name: routed
description: A modular HTTP engine and routing framework for Dart with middleware, configuration, sessions, and observability built in.
version: 0.2.0
repository: https://github.com/kingwill101/routed/tree/master/packages/routed

resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  acanthis: ^1.4.5
  collection: ^1.19.1
  contextual: ^2.0.0
  crypto: ^3.0.6
  dartastic_opentelemetry: ^0.9.3
  dartastic_opentelemetry_api: ^0.8.8
  decimal: ^3.2.4
  dotenv: ^4.2.0
  encrypt: ^5.0.3
  es_compression: ^2.0.15
  event_bus: ^2.0.1
  file: ^7.0.1
  file_cloud: ^0.1.0
  fuzzywuzzy: ^1.2.0
  http: ^1.5.0
  http2: ^2.3.1
  http_parser: ^4.1.2
  image: ^4.5.4
  intl: ^0.20.2
  jose: ^0.3.5
  json2yaml: ^3.0.1
  json_annotation: ^4.9.0
  liquify: ^1.3.0
  meta: ^1.17.0
  mime: ^2.0.0
  mustache_template: ^2.0.1
  path: ^1.9.1
  redis: ^3.1.0
  shelf: ^1.4.2
  stack_trace: ^1.12.1
  storage_fs: ^0.1.0
  timezone: ^0.10.1
  uuid: ^4.5.1
  xml: ^6.6.1
  yaml: ^3.1.3
dev_dependencies:
  lints: ^6.0.0
  property_testing: ^0.2.0
  routed_testing: ^0.2.0
  server_testing: ^0.2.0
  test: ^1.26.3
