name: server_testing_shelf
description: Adapter for the Shelf package to use server_testing for HTTP testing.
version: 0.3.2
repository: https://github.com/kingwill101/routed/tree/master/packages/server_testing_shelf
tags:
  - testing
  - shelf
  - adapter

funding:
  - https://www.buymeacoffee.com/kingwill101

resolution: workspace


environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  meta: ^1.17.0
  server_testing: ^0.3.2
  shelf: ^1.4.2

dev_dependencies:
  http_parser: ^4.1.2
  property_testing: ^0.3.2
  shelf_router: ^1.1.4
