name: server_native
description: Rust-backed transport boot APIs for Dart HTTP servers.
version: 0.1.3
homepage: https://github.com/kingwill101/routed/tree/master/packages/server_native
repository: https://github.com/kingwill101/routed
issue_tracker: https://github.com/kingwill101/routed/issues
documentation: https://github.com/kingwill101/routed/tree/master/packages/server_native#readme
tags:
  - server
  - ffi
  - rust

funding:
  - https://www.buymeacoffee.com/kingwill101

resolution: workspace

executables:
  setup:

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  archive: ^4.0.7
  code_assets: ^1.0.0
  contextual: ^2.2.0
  ffi: ^2.1.4
  hooks: ^1.0.1
  native_toolchain_rust: ^1.0.3

dev_dependencies:
  ffigen: ^20.1.1
  lints: ^6.0.0
  path: ^1.9.1
  relic: ^0.14.0
  routed: ^0.3.3
  routed_io: ^0.1.0
  shelf: ^1.4.2
  test: ^1.29.0
