name: full_stack
description: A new Routed application.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  args: ^2.5.0
  ormed: ^0.1.0-dev+7
  ormed_cli: ^0.1.0-dev+7
  ormed_sqlite: ^0.1.0-dev+7
  routed:
    path: ../../packages/routed
  routed_testing:
    path: ../../packages/server_testing/routed_testing

dev_dependencies:
  build_runner: ^2.10.5
  hotreloader: ^4.3.0
  lints: ^6.0.0
  server_testing:
    path: ../../packages/server_testing/server_testing
  test: ^1.26.3

dependency_overrides:
  routed:
    path: ../../packages/routed
  routed_testing:
    path: ../../packages/server_testing/routed_testing
  server_testing:
    path: ../../packages/server_testing/server_testing
