version: "dev"
root_view: "inertia.liquid"
history:
  encrypt: false
ssr:
  enabled: false
  url: "http://127.0.0.1:13714"
  ensure_bundle_exists: true
  runtime: "node"
assets:
  manifest_path: "client/dist/.vite/manifest.json"
  entry: "index.html"
  base_url: "/"
  hot_file: "client/public/hot"
