# Static configuration quick reference:
# enabled – Enable static asset serving. Default: false. Type: boolean
# mounts – List of static mount configurations. Default: []. Type: array

enabled: true
mounts:
  - route: /assets
    disk: public
    path: client/dist/assets