name: demo_app
description: A new Routed application.
version: 0.1.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  args: ^2.5.0
  artisanal: ^0.1.2
  routed: ^0.3.2
  routed_inertia: ^0.1.0

dev_dependencies:
  inertia_dart: ^0.1.0
  lints: ^6.0.0
  test: ^1.26.3

